### ISSUE TITLE
the errors module is not installed

### ISSUE THREAD

**Issue by daureg** [apls777/spotty#29]
There is a missing `__init__.py` in `spotty/errors` so on a fresh install I get the following error:

```
spotty --version
Traceback (most recent call last):
  File "/home/glefalher/.local/share/virtualenvs/autosuggest-analysis-JWy0ztrb/bin/spotty", line 7, in <module>
    from spotty.commands.aws import AwsCommand
  File "/home/glefalher/.local/share/virtualenvs/autosuggest-analysis-JWy0ztrb/lib/python3.7/site-packages/spotty/commands/aws.py", line 3, in <module>
    from spotty.providers.aws.commands.create_ami import CreateAmiCommand
  File "/home/glefalher/.local/share/virtualenvs/autosuggest-analysis-JWy0ztrb/lib/python3.7/site-packages/spotty/providers/aws/commands/create_ami.py", line 6, in <module>
    from spotty.providers.aws.instance_manager import InstanceManager
  File "/home/glefalher/.local/share/virtualenvs/autosuggest-analysis-JWy0ztrb/lib/python3.7/site-packages/spotty/providers/aws/instance_manager.py", line 3, in <module>
    from spotty.errors.instance_not_running import InstanceNotRunningError
ModuleNotFoundError: No module named 'spotty.errors'
```

**Comment by apls777** [comment]
Thanks, Geraud. Fixed it.
